language: php

env:
  global:
    - setup=stable
    - DB_USERNAME=root
    - DB_PASSWORD=

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COVERAGE=1
    - php: 7.2
      env: setup=lowest COVERAGE=0
    - php: 7.1
      env: COVERAGE=0
    - php: 7.1
      env: setup=lowest COVERAGE=0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS EloquentFormsTest;'

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - if [ "$COVERAGE" == "1" ]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [ "$COVERAGE" == "0" ]; then vendor/bin/phpunit; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
